dist: trusty
sudo: false

script:
  - date
  - ./process-template.sh

  - echo "Will run this SQL on org:"
  - cat update-org.sql
  - heroku pg:psql -a travis-production < update-org.sql

  - echo "Will run this SQL on com:"
  - cat update-com.sql
  - heroku pg:psql -a travis-pro-production < update-com.sql
